eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/ #把自己注册到服务中心
spring:
  application:
    name: config #服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sijidouwudi/springcloud_config.git #填写码云上已有的配置文件
          username: 1349516890@qq.com  #如果码云项目是私有的话需要加密码
          password: publicstatic0301

server:
  port: 8084

