server:
  port: 8082 #本服务的端口
spring:
  application:
    name: zuul #注册中心的服务名
zuul:
  routes:
     item-service:
       path: /item-service/** #拦截localhost:8082/item-service/**请求方式  然后转发到注册中心对应的服务id
       #url: http://localhost:8088
       serviceId: product

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

