server:
  port: 8761  #当前服务端口
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/ #表示当前项目注册到哪一个项目中心
      register-with-eureka: false #是否将自己注册到Eureka中心
spring:
  application:
    name: Eureka1      #在注册中心的名字

